/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 4
   Tile set      : D:\Users\BrianNorman\SkyDrive\gamingmonsters\gameboydev\projects\chromedino\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 32
#define mapHeight 4
#define mapBank 0

extern unsigned char map[];

/* End of MAP.H */
