/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 2
   Tile set      : D:\Users\BrianNorman\SkyDrive\gamingmonsters\gameboydev\projects\chromedino\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 64
#define mapHeight 2
#define mapBank 0

extern const unsigned char map[];

/* End of MAP.H */
